//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkhmetshinGSave
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.AgentPriorityHistory = new HashSet<AgentPriorityHistory>();
            this.ProductSale = new HashSet<ProductSale>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public int AgentTypeID { get; set; }
        public string Title { get; set; }
        public string AgentTypeTitle
        {
            get
            {
                return AgentType.Title;
            }
        }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Logo { get; set; }
        public string AgentLogo { 
            get
            {
                if (Logo == null)
                    return "agents/picture.png";
                else 
                    return Logo;
            }
        }
        public string Address { get; set; }
        public int Priority { get; set; }
        public string DirectorName { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public int SalesForYear {
            get
            {
                int sales = 0;
                foreach(ProductSale productSale in ProductSale)
                {
                    TimeSpan differenceWithoutTime = DateTime.Today.Date - productSale.SaleDate.Date;
                    if ((int)differenceWithoutTime.TotalDays <= 365)
                        sales += productSale.ProductCount;
                }
                return sales;
            }
        }
        public decimal Sales
        {
            get
            {
                decimal s = 0;
                foreach(ProductSale productSale in ProductSale)
                {
                    s += productSale.Stoimost;
                }
                return s;
            }
        }
        public int Discount
        {
            get
            {
                if (this.Sales >= 500000)
                    return 25;
                if (this.Sales >= 150000)
                    return 20;
                if (this.Sales >= 50000)
                    return 10;
                if (this.Sales >= 10000)
                    return 5;
                return 0;
            }
        }
        public string FonStyle
        {
            get
            {
                if (Discount >= 25)
                    return "LightGreen";
                else
                    return "White";
            }
        }
        public virtual AgentType AgentType { get; set; }
        public virtual ICollection<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
